### ISSUE TITLE
Chapter 5 - train.py - Runtime Memory Error

### ISSUE THREAD

**Issue by fileung** [PacktPublishing/Generative-Adversarial-Networks-Cookbook#3]
In Chapter5:
$python3 src/run.py

Traceback (most recent call last):
  File "src/run.py", line 19, in <module>
    trainer.train()
  File "Chapter5/src/train.py", line 100, in train
    X_train_A_temp = np.delete(X_train_A_temp,range(starting_ind,(starting_ind + 1)),0)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/function_base.py", line 4262, in delete
    new = arr[tuple(slobj)]
MemoryError

I am running the code from github without any changes, my GPU memory is 8GB, should be enough to run code in this book, the book GPU is only GTX 1060 6GB.

Anyone else with the same error in chapter 5?

**Comment by deepesh-packt** [comment]
Please reopen the issue if the issue still persists.
